name: Tests

on: [push, pull_request]

jobs:
  Download:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: conda-incubator/setup-miniconda@v4
        with:
          auto-update-conda: true
          channels: conda-forge
          python-version: "3.12"
          activate-environment: test
      - name: Install Pooch
        shell: bash -l {0}
        run: conda install -c conda-forge pooch
      - name: Download Files
        shell: bash -l {0}
        run: |
          cd tests
          python fetch_files.py
      - uses: actions/cache@v6
        id: filecache
        with:
          path: ./tests/data
          enableCrossOsArchive: true
          key: testfiles
  build:
    needs: Download
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.10", "3.12", "3.14"]
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Restore Cached Files
        id: cache-action
        uses: actions/cache/restore@v6
        with:
          path: ./tests/data
          key: testfiles
          enableCrossOsArchive: true
      - name: Install Conda
        uses: conda-incubator/setup-miniconda@v4
        with:
          auto-update-conda: true
          channels: conda-forge
          python-version: ${{ matrix.python-version }}
          activate_environment: test
      - name: Apple Silicon Oddities
        if: matrix.os == 'macos-latest'
        shell: bash -l {0}
        run: |
          brew install c-blosc hdf5
          export HDF5_DIF=/opt/homebrew/opt/hdf5
          export BLOSC_DIR=/opt/homebrew/opt/c-blosc
      - name: Install Dependencies
        shell: bash -l {0}
        run: |
          conda install -c conda-forge pip
          python -m pip install setuptools build
          conda install -c conda-forge cython numpy numba nbconvert pytest jupyter scipy pandas matplotlib pytables phconvert lmfit pybroom seaborn pyqt pooch
      - name: Install Project
        shell: bash -l {0}
        run:
          pip install .
      - name: Test project
        shell: bash -l {0}
        run: |
          cd notebooks
          python nbrun.py .
          cd ..
          cd tests
          python -m pytest
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    needs: build
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm, windows-latest, windows-11-arm, macos-15-intel, macos-14]
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Restore Cached Files
        id: cache-action
        uses: actions/cache/restore@v6
        with:
          path: ./tests/data
          key: testfiles
          enableCrossOsArchive: true
      - name: Build wheels
        uses: pypa/cibuildwheel@v4.2.0
        env:
          CIBW_SKIP: "cp310-win_arm64"
      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl
